version: '2'

services:
    prueba-jenkins-docker-war:
        container_name: prueba-jenkins-docker-war
        image: prueba-jenkins-docker-war
        #build:
        #    context: .
        ports:
            - "8086:8080"
        networks:
            - jenkins
        volumes:
            - /opt/demoweblogic/assets/:/usr/share/assets/
            
networks:
    jenkins:
      driver: bridge