version: '2'

services:
    pruebas-demo-weblogic-api:
        container_name: pruebas-demo-weblogic-war
        image: prueba-demo-weblogic-war
        #build:
        #    context: .
        ports:
            - "8086:8080"
        networks:
            - jenkins
        volumes:
            - /opt/demoweblogic/assets/:/usr/share/assets/
            
networks:
    jenkins:
      driver: bridge